### ISSUE TITLE
Wondering what happened and what you recommend

### ISSUE THREAD

**Issue by ryancwalsh** [dopyoman/laravel-server#2]
See https://stackoverflow.com/q/58348934/470749

I found https://github.com/dopyoman/laravel-server and funnily *then* found https://www.reddit.com/r/laravel/comments/83njsz/scripts_for_provisioning_a_bare_metal_server_for/dvk8uil/, where you pointed to https://github.com/laravel/settler/blob/master/scripts/provision.sh, which was what I'd seen one time but couldn't remember and was basically looking for.

But people gave you such critical feedback, saying that Homestead and Vagrant are insecure, and nobody should use scripts like these for production environments.

I'm wondering what you've learned since then?

Do you have any recommendations for me?

Thanks!

**Comment by devSarry** [comment]
Hmm... it's been a few years since I've touched this or a Laravel project but basically the question you are asking is would I use this to provision a server again?

Probably not. These scripts to my knowledge were secure when I wrote them, but today many of the packages are out of date. What the some of the people said in the reddit post is very true. Using a provisioning tool like ansible or whatever is better. These tools make  keeping server dependencies up to date easy. 

You can look at these to get an idea of what needs to be done to provision a single server php app but I would not advise you use this in production without vetting every line of the script.

One more thing I would like to make sure is very clear. If you run these scripts you are are putting your DB and php server in the same instance. So you need to make sure you're use case is super small and you have no intentions of scaling whatever application you are building.

Hope that helps.

**Comment by ryancwalsh** [comment]
Thanks!
